# Generated by Django 4.2.1 on 2023-05-21 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
