# Generated by Django 4.2.1 on 2023-05-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
