# Generated by Django 4.2.1 on 2023-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cover',
            field=models.ImageField(default=2, upload_to='cover_product/'),
            preserve_default=False,
        ),
    ]
