# Generated by Django 4.2.1 on 2023-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=2, upload_to='cover_category/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='featured_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
