# Generated by Django 4.2.1 on 2023-05-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image_productmodel_featured_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='shor_description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
