# Generated by Django 4.2.1 on 2023-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_imagemodel_alter_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cover_products/'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cover_products/'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='cover_products/'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='cover_products/'),
        ),
    ]
